export const GET_ERRORS = "GET_ERRORS";
export const RESET_ERRORS = "RESET_ERRORS";
export const SET_AUTH_LOADING = "SET_AUTH_LOADING";
export const UNSET_AUTH_LOADING = "UNSET_AUTH_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const SET_SNACK = "SET_SNACK";

export const SET_TAGS = "SET_TAGS";
export const SET_TAGS_LOADING = "SET_TAGS_LOADING";
export const UNSET_TAGS_LOADING = "UNSET_TAGS_LOADING";
